'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CattleManage_Batch

    '''<summary>
    '''FileUpload_excel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload_excel As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''LinkButton_import control.
    '''</summary>
    Protected WithEvents LinkButton_import As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HyperLink_template control.
    '''</summary>
    Protected WithEvents HyperLink_template As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LinkButton_downloadFailed control.
    '''</summary>
    Protected WithEvents LinkButton_downloadFailed As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Label_message control.
    '''</summary>
    Protected WithEvents Label_message As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_success control.
    '''</summary>
    Protected WithEvents Panel_success As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label_successCount control.
    '''</summary>
    Protected WithEvents Label_successCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_success control.
    '''</summary>
    Protected WithEvents GridView_success As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Panel_failed control.
    '''</summary>
    Protected WithEvents Panel_failed As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label_failedCount control.
    '''</summary>
    Protected WithEvents Label_failedCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_failed control.
    '''</summary>
    Protected WithEvents GridView_failed As Global.System.Web.UI.WebControls.GridView
End Class
